### PR TITLE
Add an option to use Azure Storage for visualization images

### PR DESCRIPTION
**Pull request by namabile**
Adds the options to use the [azure-storage](https://github.com/Azure/azure-storage-node) Node.js SDK for storing visualizations in Microsoft Azure Storage.

### CODE REVIEW

**Comment by wilg** [comment]
Awesome! Thank you so much for the contribution! Looks great!

**Comment by Ryan-C-Lee** [comment]
Hey @namabile just curious how long this took you? We are investigating getting this working with Google Cloud storage as an option. Thanks!

**Comment by namabile** [comment]
Hey @Ryan-C-Lee It was pretty quick. About an hour. I would use the the GCS option too if someone wanted to take a crack at it.

**Comment by Ryan-C-Lee** [comment]
Thanks @namabile I'm trying to get someone here to take a crack at it, but no luck so far. Here's the documentation if you have any interest: https://github.com/GoogleCloudPlatform/google-cloud-node#cloud-storage-beta :)

**Comment by Ryan-C-Lee** [comment]
In case you are interested @namabile .  https://github.com/looker/looker-slackbot/pull/69 for GCP.

**Pull request merged**
